
class Hogar
class Camion
class Carro
class Rana
class Actualizable
class Dibujo
class Sprite
class Ventana 

Rana--|>Dibujo
Rana--o Actualizable
Dibujo <|-- Carro
Actualizable o-- Carro
Dibujo <|-- Hogar
Actualizable o-- Hogar
Dibujo <|-- Camion
Actualizable o-- Camion
Sprite--|>Dibujo